[package]
name = "PredictionMarket"
version = "1.0.0"
authors = ["Darkpool Labs"]

[addresses]
prediction_market = "_"

[dev-addresses]
prediction_market = "0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "mainnet"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "mainnet"
